#
# Translation of plpython to Italian
# PostgreSQL Project
#
# Associazione Culturale ITPUG - Italian PostgreSQL Users Group
# http://www.itpug.org/ - info@itpug.org
#
# Traduttori:
#  * Flavio Spada <f.spada@sbv.mi.it>
#
# Revisori:
#  * Gabriele Bartolini <gabriele.bartolini@2ndQuadrant.it>
#
# Copyright (c) 2010, Associazione Culturale ITPUG
# Distributed under the same license of the PostgreSQL project
#
msgid ""
msgstr ""
"Project-Id-Version: plpython (PostgreSQL) 9.2\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2012-10-21 22:39+0000\n"
"PO-Revision-Date: 2010-03-27 12:44:19+0100\n"
"Last-Translator: Gabriele Bartolini <gabriele.bartolini@2ndquadrant.it>\n"
"Language-Team: Gruppo traduzioni ITPUG <traduzioni@itpug.org>\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: KBabel 1.11.4\n"

#: plpy_cursorobject.c:98
#, fuzzy, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.execute si aspetta una query o un plan"

#: plpy_cursorobject.c:171
#, fuzzy, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.execute richiede una sequenza come secondo argomento"

#: plpy_cursorobject.c:187 plpy_spi.c:222
#, c-format
msgid "could not execute plan"
msgstr "impossibile eseguire il piano"

#: plpy_cursorobject.c:190 plpy_spi.c:225
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Sequenza attesa per l'argomento %d, ricevuto %d: %s"
msgstr[1] "Sequenza attesa di %d argomenti, ricevuti %d: %s"

#: plpy_cursorobject.c:340
#, fuzzy, c-format
msgid "iterating a closed cursor"
msgstr "posiziona un cursore"

#: plpy_cursorobject.c:348 plpy_cursorobject.c:415
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr ""

#: plpy_cursorobject.c:407
#, fuzzy, c-format
msgid "fetch from a closed cursor"
msgstr "chiudi un cursore"

#: plpy_cursorobject.c:486
#, fuzzy, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr "esegui la transazione corrente"

#: plpy_elog.c:103 plpy_elog.c:104 plpy_plpymodule.c:420
#, c-format
msgid "%s"
msgstr "%s"

#: plpy_exec.c:90
#, c-format
msgid "unsupported set function return mode"
msgstr "modalità di ritorno della funzione set non supportata"

#: plpy_exec.c:91
#, c-format
msgid "PL/Python set-returning functions only support returning only value per call."
msgstr "le funzioni set-returning di PL/Python supportano il valore di ritorno solo una volta per chiamata"

#: plpy_exec.c:103
#, c-format
msgid "returned object cannot be iterated"
msgstr "l'oggetto ritornato non può essere iterato"

#: plpy_exec.c:104
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "le funzioni set-returning di PL/Python devono tornare un oggetto iterabile"

#: plpy_exec.c:129
#, c-format
msgid "error fetching next item from iterator"
msgstr "errore nell'ottenere l'elemento successivo dall'iteratore"

#: plpy_exec.c:164
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "la funzione PL/Python con valore di ritorno \"void\" non ha restituito None"

#: plpy_exec.c:288 plpy_exec.c:314
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "valore di ritorno inatteso dalla prodedura di trigger"

#: plpy_exec.c:289
#, c-format
msgid "Expected None or a string."
msgstr "Atteso None o una stringa."

#: plpy_exec.c:304
#, c-format
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "la funzione PL/Python trigger ha restituito \"MODIFY\" in un trigger DELETE -- ignorato"

#: plpy_exec.c:315
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Atteso None, \"OK\", \"SKIP\", o \"MODIFY\"."

#: plpy_exec.c:396
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "PyList_SetItem() è fallita durante l'impostazione degli argomenti"

#: plpy_exec.c:400
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "PyDict_SetItemString() è fallita durante l'impostazione degli argomenti"

#: plpy_exec.c:412
#, c-format
msgid "function returning record called in context that cannot accept type record"
msgstr "la funzione che restituisce un record è chiamata all'interno di un contesto che non può accettare il tipo record"

#: plpy_exec.c:450
#, c-format
msgid "while creating return value"
msgstr "durante la creazione del valore di ritorno"

#: plpy_exec.c:474
#, c-format
msgid "could not create new dictionary while building trigger arguments"
msgstr "impossibile creare un nuovo dizionario mentre si stanno costruendo gli argomenti del trigger"

#: plpy_exec.c:664
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] cancellato, impossibile modificare la riga"

#: plpy_exec.c:667
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] non è un dizionario"

#: plpy_exec.c:691
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "la chiave di dizionario TD[\"new\"] alla posizione %d non è una stringa"

#: plpy_exec.c:697
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr "la chiave \"%s\" trovata in TD[\"new\"] non esiste come colonna nella riga del trigger"

#: plpy_exec.c:778
#, c-format
msgid "while modifying trigger row"
msgstr "durante la modifica della riga trigger"

#: plpy_exec.c:839
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr ""

#: plpy_main.c:100
#, c-format
msgid "Python major version mismatch in session"
msgstr ""

#: plpy_main.c:101
#, c-format
msgid "This session has previously used Python major version %d, and it is now attempting to use Python major version %d."
msgstr ""

#: plpy_main.c:103
#, c-format
msgid "Start a new session to use a different Python major version."
msgstr ""

#: plpy_main.c:118
#, c-format
msgid "untrapped error in initialization"
msgstr "errore non catturato durante l'inizializzazione"

#: plpy_main.c:141
#, c-format
msgid "could not import \"__main__\" module"
msgstr "impossibile importare il modulo \"__main__\""

#: plpy_main.c:146
#, fuzzy, c-format
msgid "could not create globals"
msgstr "impossibile inizializzare le variabili globali"

#: plpy_main.c:150
#, c-format
msgid "could not initialize globals"
msgstr "impossibile inizializzare le variabili globali"

#: plpy_main.c:347
#, c-format
msgid "PL/Python function \"%s\""
msgstr "funzione PL/Python \"%s\""

#: plpy_main.c:354
#, c-format
msgid "PL/Python anonymous code block"
msgstr "codice di blocco anonimo in PL/Python"

#: plpy_planobject.c:126
#, c-format
msgid "plan.status takes no arguments"
msgstr "plan.status non accetta argomenti"

#: plpy_plpymodule.c:178 plpy_plpymodule.c:181
#, fuzzy, c-format
msgid "could not import \"plpy\" module"
msgstr "impossibile importare il modulo \"__main__\""

#: plpy_plpymodule.c:196
#, fuzzy, c-format
msgid "could not add the spiexceptions module"
msgstr "impossibile importare il modulo \"__main__\""

#: plpy_plpymodule.c:217
#, fuzzy, c-format
msgid "could not create the base SPI exceptions"
msgstr "impossibile creare il socket: %s\n"

#: plpy_plpymodule.c:253 plpy_plpymodule.c:257
#, fuzzy, c-format
msgid "could not generate SPI exceptions"
msgstr "impossibile localizzare un record di checkpoint valido"

#: plpy_plpymodule.c:388
#, fuzzy, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "impossibile interpretare il messaggio di errore in plpy.elog"

#: plpy_plpymodule.c:396
msgid "could not parse error message in plpy.elog"
msgstr "impossibile interpretare il messaggio di errore in plpy.elog"

#: plpy_procedure.c:194
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "le funzioni trigger possono essere chiamate solo come trigger"

#: plpy_procedure.c:199 plpy_typeio.c:406
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "le funzioni PL/Python non possono tornare il tipo %s"

#: plpy_procedure.c:281
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "le funzioni PL/Python non possono accettare il tipo %s"

#: plpy_procedure.c:377
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "impossibile compilare la funzione PL/Python \"%s\""

#: plpy_procedure.c:380
#, fuzzy, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "impossibile compilare la funzione PL/Python \"%s\""

#: plpy_resultobject.c:145 plpy_resultobject.c:165 plpy_resultobject.c:185
#, c-format
msgid "command did not produce a result set"
msgstr ""

#: plpy_spi.c:56
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "il secondo argomento di plpy.prepare deve essere una sequenza"

#: plpy_spi.c:105
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: il nome del tipo nella posizione %d non è una stringa"

#: plpy_spi.c:137
#, c-format
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare non supporta tipi composti"

#: plpy_spi.c:187
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute si aspetta una query o un plan"

#: plpy_spi.c:206
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute richiede una sequenza come secondo argomento"

#: plpy_spi.c:330
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan ha fallito: %s"

#: plpy_spi.c:372
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute ha fallito: %s"

#: plpy_spi.c:439
#, c-format
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "errore non riconosciuto nella funzione PLy_spi_execute_fetch_result"

#: plpy_subxactobject.c:122
#, c-format
msgid "this subtransaction has already been entered"
msgstr ""

#: plpy_subxactobject.c:128 plpy_subxactobject.c:180
#, c-format
msgid "this subtransaction has already been exited"
msgstr ""

#: plpy_subxactobject.c:174
#, fuzzy, c-format
msgid "this subtransaction has not been entered"
msgstr "il tipo del record non è stato registrato"

#: plpy_subxactobject.c:186
#, fuzzy, c-format
msgid "there is no subtransaction to exit from"
msgstr "non c'è nessuna transazione in corso"

#: plpy_typeio.c:291
#, c-format
msgid "could not create new dictionary"
msgstr "impossibile creare il nuovo dizionario"

#: plpy_typeio.c:408
#, c-format
msgid "PL/Python does not support conversion to arrays of row types."
msgstr ""

#: plpy_typeio.c:584
#, c-format
msgid "cannot convert multidimensional array to Python list"
msgstr ""

#: plpy_typeio.c:585
#, c-format
msgid "PL/Python only supports one-dimensional arrays."
msgstr ""

#: plpy_typeio.c:591
#, fuzzy, c-format
msgid "could not create new Python list"
msgstr "impossibile creare il nuovo dizionario"

#: plpy_typeio.c:650
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "impossibile creare la rappresentazione di tipo byte dell'oggetto Python"

#: plpy_typeio.c:742
#, c-format
msgid "could not create string representation of Python object"
msgstr "impossibile creare la rappresentazione di tipo stringa dell'oggetto Python"

#: plpy_typeio.c:753
#, c-format
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr ""

#: plpy_typeio.c:787
#, c-format
msgid "return value of function with array return type is not a Python sequence"
msgstr ""

#: plpy_typeio.c:886
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "la chiave \"%s\" non è stata trovata nel dizionario"

#: plpy_typeio.c:887
#, c-format
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr "Per ritornare null in una colonna, inserire nella mappa il valore None in corrispondenza del nome di colonna come chiave."

#: plpy_typeio.c:935
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr "la lunghezza della sequenza ritornata non rispetta il numero di colonne presenti nella riga"

#: plpy_typeio.c:1043
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "l'attributo \"%s\" non esiste nell'oggetto Python"

#: plpy_typeio.c:1044
#, c-format
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr "Per ritornare null in una colonna, assicurarsi che all'oggetto di ritorno corrisponda nel dizionario un attributo con valore None."

#: plpy_util.c:70
#, fuzzy, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "impossibile convertire \"%s\"in un fuso orario"

#: plpy_util.c:75
#, fuzzy, c-format
msgid "could not extract bytes from encoded string"
msgstr "impossibile confrontare stringhe in Unicode :%m"

#~ msgid "PL/Python function \"%s\" failed"
#~ msgstr "la funzione PL/Python \"%s\" è fallita"

#~ msgid "could not create string representation of Python object in PL/Python function \"%s\" while creating return value"
#~ msgstr "impossibile creare una rappresentazione di tipo stringa dell'oggetto Python nella funzione PL/Python \"%s\" durante la creazione del valore di ritorno"

#~ msgid "could not compute string representation of Python object in PL/Python function \"%s\" while modifying trigger row"
#~ msgstr "impossibile calcolare la rappresentazione di tipo stringa dell'oggetto Python nella funzione PL/Python \"%s\" mentre si sta modificando la riga di trigger"

#~ msgid "out of memory"
#~ msgstr "memoria esaurita"

#~ msgid "PL/Python: %s"
#~ msgstr "PL/Python: %s"

#~ msgid "could not create procedure cache"
#~ msgstr "impossibile creare la procedura cache"

#~ msgid "unrecognized error in PLy_spi_execute_query"
#~ msgstr "errore non riconosciuto nella funzione PLy_spi_execute_query"

#~ msgid "unrecognized error in PLy_spi_execute_plan"
#~ msgstr "errore non riconosciuto nella funzione PLy_spi_execute_plan"

#~ msgid "unrecognized error in PLy_spi_prepare"
#~ msgstr "errore non riconosciuto in PLy_spi_prepare"

#~ msgid "invalid arguments for plpy.prepare"
#~ msgstr "argomenti non validi per plpy.prepare"

#~ msgid "transaction aborted"
#~ msgstr "transazione abortita"
